import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import { CartProvider } from '../context/CartContext';
import { ToastProvider } from '../context/ToastContext';
import { AdminProvider } from '../contexts/AdminContext';
import CartModal from '../components/CartModal';

// Configuração da fonte Montserrat
const montserrat = Montserrat({ 
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <ToastProvider>
          <CartProvider>
            <AdminProvider>
              {children}
              <CartModal />
            </AdminProvider>
          </CartProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
